### ISSUE TITLE
Tests fail because utils/make-phar.php isn't accessible

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/package-command#1]
See https://travis-ci.org/wp-cli/package-command/builds/209899744

```
01. $ php -dphar.readonly=0 'features/bootstrap/../../utils/make-phar.php' '/tmp/wp-cli-test-run-58c317feeaf023.95759079/wp-cli-build-58c317feeaff24.74413409.phar' --version='0.23.0' && chmod +x '/tmp/wp-cli-test-run-58c317feeaf023.95759079/wp-cli-build-58c317feeaff24.74413409.phar'
    Could not open input file: features/bootstrap/../../utils/make-phar.php
```

Which option makes more sense?

1. Include `utils/make-phar.php` as a one-off in this repo.
2. Add `utils/make-phar.php` to `wp scaffold package-tests` so that the Phar creation step is available to every WP-CLI command.
3. Add `utils/make-phar.php` to the generated WP-CLI Phar file, so that it's available 

I'm leaning towards 3 at this point, so there's always one source of truth for Phar generation.

**Comment by danielbachhuber** [comment]
@schlessera What's your opinion?

**Comment by schlessera** [comment]
@danielbachhuber I don't completely like any of the three, but I think 3 is indeed the best option so far. Although it is used in the tests, it is logically part of the build toolchain.

A fourth option would be to have the build toolchain for WP-CLI be in a separate package that is required as a dev-dependency in WP-CLI as well as in external packages that need it. It doesn't need to be part of the runtime source for any of them.

**Comment by danielbachhuber** [comment]
> I think 3 is indeed the best option so far. Although it is used in the tests, it is logically part of the build toolchain.

Not so easy, as it turns out. Even if we include `utils/make-phar.php` in the Phar file, we can't call it directly.

But, we could install WP-CLI in Travis via Composer, and then everything will be available to us.

**Comment by danielbachhuber** [comment]
Approaching this in a new way:

1. Installing WP-CLI for tests by adding `wp-cli/wp-cli` as a project dependency: https://github.com/wp-cli/scaffold-package-command/pull/89
2. Making use of the `utils/make-phar.php` included with the `wp-cli/wp-cli` dependency: https://github.com/wp-cli/package-command/pull/2
