### ISSUE TITLE
installing package on Intranet

### ISSUE THREAD

**Issue by Yoshiro-Sasagawa** [wp-cli/package-command#102]
Hi, very much appreciate for this.

I can't figure out how to install my package.
It says "https://wp-cli.org/package-index/packages.json file could not be downloaded"
when "wp package install <path>" cause its on a intranet.

Is there any way to install my package manualy? or avoid to connect out side of network. 

I tried to install from zip but doesn't work.
path to "composer" is globaly added and "wp" command too.

thanks.

**Comment by swissspidy** [comment]
What issues did you get when trying to install from ZIP?

Could you configure your local setup to use a proxy or anything? See: https://github.com/wp-cli/wp-cli/issues/3019.

With that being said:

GitHub issues are meant for tracking enhancements to and bugs of existing commands, not general support.

I suggest you to join the #cli channel in the [WordPress.org Slack](https://make.wordpress.org/chat/) to chat with whomever might be available at the time. This option is best for quick questions.

**Comment by schlessera** [comment]
> I suggest you to join the #cli channel in the WordPress.org Slack to chat with whomever might be available at the time. This option is best for quick questions.

Yes, please join us on Slack, and we'll help you go through your options.

**Comment by Yoshiro-Sasagawa** [comment]
Thanks.

I'll take a look into proxy option and Slack.
Just for a reference, I've put my package into user directory like C:¥Users¥me¥.wp-cli then "wp package list" shows it and custom command works well though I'm sure it's not a good way.
(changing directories were needed)
