### ISSUE TITLE
Allow install from a Git repository specific branch

### ISSUE THREAD

**Issue by drzraf** [wp-cli/package-command#109]
## Feature Request 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I would like to install a command from a remote repository **non-master branch**.
Eg: I forked a built-in `wp-cli` command and my changes are not merged (yet) but available in my own repository (but on a custom branch).

**Describe the solution you'd like**

Using my package's flavor on a remote machine could be as simple as:
`wp package install https://github.com/my/export-command.git:@my-forked-branch`
(But alternative syntax could be even better)

**Comment by schlessera** [comment]
This works already, but you need to use the branch syntax that Composer uses (the package manager is basically just an embedded version of Composer).

For example, I could successfully pull in one of your branches with the following command:
```
wp package install "drzraf/export-command:dev-select-export-sections"
```

**Comment by edpittol** [comment]
The name of the branch is defined after `dev-`. In the example above, the branch is `select-export-sections`.

**Comment by ernilambar** [comment]
We could add an example for installing package from different branch of a repo.
