### ISSUE TITLE
check_git_package_name hardcode reference to GitHub

### ISSUE THREAD

**Issue by drzraf** [wp-cli/package-command#110]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`wp package install https://gitlab.com/my/package.git`

=>
```
Warning: Couldn't download composer.json file from 'https://raw.githubusercontent.com/my/package/master/composer.json' (HTTP code 404).
Presuming package name is 'my/package'.
```

Repository is at **gitlab**.com, "real" name must not be checked at raw.**github**usercontent.com

This breaks further package name resolution if the repository name is not the same than the package name.

**Comment by schlessera** [comment]
What is the best way to fetch a singular file from Gitlab in this case? Is there a URL like the `raw.githubusercontent.com` one, where we can easily fetch a singular file without hitting the API or git directly?

**Comment by drzraf** [comment]
Sure, `https://gitlab.com/<repository-group/[subgroup/]name>/raw/master/composer.json`
