### ISSUE TITLE
Allow composer ^2.0

### ISSUE THREAD

**Issue by mremi** [wp-cli/package-command#142]
Hi,

Would it be possible to support composer ^2.0 instead of ^2.0.0? Thus allowing versions >=2.0 and <3.0.

Thanks

**Comment by schlessera** [comment]
You seem to be confusing the caret operator `^` with the tilde operator `~`. The version constraint already does what you want.

**Comment by stefanfisk** [comment]
@schlessera I just encountered this issue as well, and I believe that your statement is incorrect?

`~2.2.17` does not allow installing `composer/composer:2.5.1`, for that to work you would need to use `~2.2`: https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

**Comment by schlessera** [comment]
@stefanfisk I was replying to @mremi that `^2.0.0` already does what he wants. He did not use the tilde operator, therefore, no need to avoid the patch version.

**Comment by schlessera** [comment]
Ah, I see the issue now, WP-CLI does use the tilde operator. Sorry about the confusion, the original report was using the wrong operator.
I'll adapt the version constraint.

**Comment by stefanfisk** [comment]
@schlessera having the `composer.json` open in another tab must have been too much of a bias for my overworked brain to actually parse your original answer 😸

**Comment by stefanfisk** [comment]
@schlessera do you have an ETA for when the version constraint will allow `composer/composer:2.5.1`? This is currently blocking me from updating a bunch of stuff.
