### ISSUE TITLE
Support for Composer 2.5

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/package-command#172]
We should update `wp-cli/package-command` so it can be installed where `composer/composer` 2.5 is a dependency.

From https://github.com/wp-cli/package-command/pull/167#issuecomment-1435612094

**Done is:**
* `wp-cli/package-command` supports `composer/composer:~2.5`.

**Comment by stefanfisk** [comment]
@danielbachhuber do you know anything specific that needs fixing, or is it just untested?

**Comment by danielbachhuber** [comment]
@stefanfisk I think some fixes are needed for this: https://github.com/wp-cli/package-command/actions/runs/4189588371/jobs/7262087460#step:13:318

**Comment by stefanfisk** [comment]
@danielbachhuber cool, that looks easy enough. Is it OK to go with only `^2.5.4`, or is `^1.10.23` still needed as well?

**Comment by danielbachhuber** [comment]
@stefanfisk We can remove `^1.10.23` as long as there aren't any backwards-compat issues.

**Comment by stefanfisk** [comment]
@danielbachhuber so after making the changes required I found some old related issues where this exact change was abandoned because Composer 2.3 is not compatible with PHP 5.6: https://github.com/wp-cli/package-command/pull/151 https://github.com/wp-cli/package-command/issues/152

So as long as PHP 5.6 compatibility is required this is not fixable. I'm not familiar with the PHP compatibility policy for WP-CLI, is PHP 5.6 compatiblity still required? And if it is, is there any end date for said compatiblity requirement? 5.6 is absolutely ancient by now :/

**Comment by danielbachhuber** [comment]
> so after making the changes required I found some old related issues where this exact change was abandoned because Composer 2.3 is not compatible with PHP 5.6:

@stefanfisk Ah, good find.

> So as long as PHP 5.6 compatibility is required this is not fixable. I'm not familiar with the PHP compatibility policy for WP-CLI, is PHP 5.6 compatiblity still required? And if it is, is there any end date for said compatiblity requirement? 5.6 is absolutely ancient by now :/

We'll need to support support PHP 5.6 at least as long as WordPress core supports 5.6. Fortunately, [that should be over soon](https://core.trac.wordpress.org/ticket/57345).

In 2019, our plan was to [support PHP 5.6 for at least a year after core removed support](https://make.wordpress.org/cli/2019/01/15/wp-cli-php-requirements-strategy/). It seems like we may need to revisit that, though.

**Comment by stefanfisk** [comment]
As a workaround, I switch from `wp-cli-bundle` to requiring the individual packages except for `package-command`.

It's a bit ugly, but would you be OK with having to implementations of `ComposerIO`, one with types and one without, and then have [ComposerIO.php](https://github.com/wp-cli/wp-cli/blob/main/php/WP_CLI/ComposerIO.php) require the correct one based on `PHP_MAJOR_VERSION`?

**Comment by danielbachhuber** [comment]
> It's a bit ugly, but would you be OK with having to implementations of `ComposerIO`, one with types and one without, and then have [ComposerIO.php](https://github.com/wp-cli/wp-cli/blob/main/php/WP_CLI/ComposerIO.php) require the correct one based on `PHP_MAJOR_VERSION`?

@stefanfisk Yes, that would be a perfectly fine approach
