### ISSUE TITLE
Documentation about where packages get installed to

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/package-command#18]
When you installed a package using, for example, `wp package install git@github.com:wp-cli/scaffold-package-command.git`, the command gets installed into `~/.wp-cli/packages/vendor/wp-cli/scaffold-package-command` but I had to do some hunting around to find out that this was the case.

This is particularly useful information for people who want to contribute to a community package.

**Comment by emirpprime** [comment]
It would be great to include the related info here too: https://danielbachhuber.com/tip/shared-wp-cli-packages/
The info on working with multiple users and a shared package dir is really helpful.

**Comment by danielbachhuber** [comment]
@johnbillion Where would you expect to find this documentation?

**Comment by johnbillion** [comment]
I would say within the `wp package install` help docs.

**Comment by danielbachhuber** [comment]
> It would be great to include the related info here too: https://danielbachhuber.com/tip/shared-wp-cli-packages/

I think this is probably too much information to try to include in the command docs. We could link to it though.
