### ISSUE TITLE
Version requirements only work for the package index

### ISSUE THREAD

**Issue by schlessera** [wp-cli/package-command#20]
The current parsing code that tries to identify the package only allows for version constraints when using the package index. For git repositories, it just fails with an `Error: Invalid package.`.

Ideally, the parsing should accept any string that the underlying Composer would be able to handle, with a fallback to building a proper GitHub URL for shortened syntax to account for the package index deprecation.

**Comment by danielbachhuber** [comment]
@schlessera Moving this out of the milestone, given there isn't a pull request for it yet. We can land whenever it's ready.

**Comment by schlessera** [comment]
@danielbachhuber The functionality was already in there since https://github.com/wp-cli/package-command/pull/22 was merged, due to the way I implemented that one. I hadn't closed the issue yet because I still had to create test cases to actually test all the scenarios.

All tests ran successfully, so this was working for some time now.
