### ISSUE TITLE
Uninstallation leaves VCS repository behind

### ISSUE THREAD

**Issue by schlessera** [wp-cli/package-command#25]
When you install a package from a VCS repository, WP-CLI first adds that repository to its `composer.json` file, and then `require`s the package.

On unistallation, the `require` statement is correctly removed, but the VCS repository setting that was added is left behind. This can then break subsequent package manager operations, depending on where that setting is pointing to and what has happened to the related repository.

As an example, having a VCS repository setting in `composer.json` that points to a GitHub repository that has since been deleted makes all package manager operations fail because Composer fatals.

**Comment by danielbachhuber** [comment]
This was fixed in #37
