### ISSUE TITLE
Improve 'wp package' command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/package-command#30]
Improve command description in:
https://github.com/wp-cli/package-command/blob/master/src/Package_Command.php
Command: wp package
Current description: Manage WP-CLI packages.

Proposed description:
Runs WP-CLI package manager commands.

**Comment by miya0001** [comment]
Can you give us a pull-request?

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by miya0001** [comment]
It fixed at https://github.com/wp-cli/package-command/pull/32.
Thanks @hearvox 😊
