### ISSUE TITLE
Packages installed from git where the git user has capital letters don't show up in `package list`

### ISSUE THREAD

**Issue by javorszky** [wp-cli/package-command#43]
I've created an example command here: https://github.com/CapitalWPCLI/examplecommand

## To reproduce:

1. `wp package install git@github.com:CapitalWPCLI/examplecommand.git`
2. `wp package list`, see that it is not in the list
3. go and look at the `composer.json` file in `~/wp-cli/packages` folder. See that the package's key is the github user : repository
4. because of the [code that lists the packages](https://github.com/wp-cli/package-command/blob/master/src/Package_Command.php#L735-L739) matches the package id (all lowercase) with what's in the composer json, it will not be matched.

## Environment

```
$ uname -a
Darwin GaborrMBP 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

$ which -a php
/usr/local/bin/php
/usr/bin/php

$ php -v
PHP 7.1.10 (cli) (built: Oct  6 2017 01:08:53) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

no suhosin

Which version of WordPress
none, not specific

$ which -a wp
stat $(which wp)
/usr/local/bin/wp
16777220 56521130 -rwxr-xr-x 1 javorszky staff 0 4292472 "Oct 15 13:03:17 2017" "Sep 10 17:58:46 2017" "Sep 27 16:50:55 2017" "Sep 10 17:58:44 2017" 4194304 8384 0 /usr/local/bin/wp
```

Hope this is enough information.

**Comment by javorszky** [comment]
From the looks of it, this piece of code should handle the mismatch:

https://github.com/wp-cli/package-command/blob/master/src/Package_Command.php#L221-L227

But for some reason doesn't.

**Comment by gitlost** [comment]
Thanks for the excellent example and diagnostics @javorszky.

> this piece of code should handle the mismatch

Composer is doing `strtolower()`s all over the place for some reason so the package name gets "corrected" to its lowercase version.

A way around might be to do `$installed_package_keys = array_map( 'strtolower', $installed_package_keys );` in `get_installed_packages()`, and also to lowercase the `$package_name` arg in `get_installed_package_by_name()` and (for the BC check only) `get_package_by_shortened_identifier()`.

**Comment by javorszky** [comment]
I think the install script is wrong. It compares the package name in the composer.json in the repo with the name of the repo, and if the two don't match, it uses the name in the composer.json.

Or at least should. If you look in the composer.json of the example command, that one is all lowercase because composer complains otherwise.

Yet what does get installed / recorded is the repo name, so the comparison goes wrong there. I think. I don't have wpcli set up for dev on my computer, so can't double check this with debugging statements.

**Comment by gitlost** [comment]
> I think the install script is wrong. It compares the package name in the composer.json in the repo with the name of the repo, and if the two don't match, it uses the name in the composer.json.

Ah maybe it shouldn't then. If I change that check to `if ( strtolower( $package_name ) !== $package_name_on_repo ) {` then things kind of work okay, ie the `require` etc keys in `~/wp.cli/packages/composer.json` all have the non-lowercased name.

And with the `strtolower()` hacks mentioned earlier can uninstall okay as long as I specify the correct case.

The listing is wrongly in lowercase though.

**Comment by javorszky** [comment]
What I mean is that if the github is `CapitalWPCLI/examplecommand`, and the composer json has `capitalwpcli/examplecommand` as the name, it should save as `capitalwpcli/examplecommand`.

Currently it saves as `CapitalWPCLI/examplecommand`.

**Comment by javorszky** [comment]
To be fair, I expect the `~/.wp-cli/package/composer.json` would have the name of the package as it's declared in the `composer.json` of the package.

**Comment by gitlost** [comment]
Okay, ta. It's very confusing and messy. I'll leave it to the Composer experts, of which I'm most definitely not. Related https://github.com/wp-cli/wp-cli/issues/4232 and https://github.com/wp-cli/package-command/pull/31

**Comment by javorszky** [comment]
Okies. I summon @schlessera / @danielbachhuber to take a glance at this if they have a moment :)

**Comment by gitlost** [comment]
Mystery solved - just noticed the **4292472** in your stat of wp - that's the size of wp-cli 1.3.0 - and https://github.com/wp-cli/package-command/pull/31 is only in 1.4.0, so that's why the mixed case git user name is ending up in your composer.json, as it's not getting corrected by mismatch check in the lines you highlighted.

I'll add a test anyway to clarify this situation (for myself mostly, given the confusion I got myself into above).

**Comment by javorszky** [comment]
Ooh, okay. That makes sense! Thank you. An uh... sorry for not checking the versions! Should I leave this open until the tests are added?

**Comment by gitlost** [comment]
Hi, thanks for getting back. Please leave it open yes, as I've found out that there is an issue after all with mixed-case names with the current version, though not in your particular case (but when the name in `composer.json` is mixed-case anyway).

I'm going to do a PR very soon with a fix for that case, and also with tests for that case and your case. The tests will use your test example https://github.com/CapitalWPCLI/examplecommand if that's alright. Also if and when you have the time if you could confirm that updating to the latest wp-cli fixes your issue it'd be much appreciated.

**Comment by javorszky** [comment]
Will do! I'll keep an eye out for the new versions of wp-cli! Thank you for looking into this!

**Comment by gitlost** [comment]
Ta - just in case to clarify, the current version 1.4.0 should fix your issue so you don't have to wait to confirm it!

**Comment by javorszky** [comment]
Hi,

So it didn't work... seemingly it did. Also, if I'm installing a specific package, it shouldn't update all the others, right?

<img width="840" alt="screen shot 2017-11-03 at 15 02 23" src="https://user-images.githubusercontent.com/1196299/32380524-2bdb5f92-c0a8-11e7-9b00-a06e8061d848.png">

This is using wpcli 1.4.0

**Comment by javorszky** [comment]
Nope, ignore the above. Once I removed the package manually (delete files, delete composer.lock, edit composer.json), and tried again, it installed the package correctly.

However I can no longer test updating other packages when I'm installing one...

**Comment by danielbachhuber** [comment]
> Also, if I'm installing a specific package, it shouldn't update all the others, right?

Incorrect. This is expected behavior, as WP-CLI uses Composer under the hood.

**Comment by gitlost** [comment]
> Once I removed the package manually (delete files, delete composer.lock, edit composer.json)

Yes, that's the sort of thing I ended up doing too, which I thought was probably just my system having got messed up.

**Comment by gitlost** [comment]
> This is expected behavior

Maybe it shouldn't though?! It seems odd to me that installing a package causes a full install using `~/.wp-cli/packages/composer.json` rather than just the packages `composer.json` (but I'll have to think about it and come up with something less half-formed - and this probably isn't the best place to discuss it anyway).

**Comment by schlessera** [comment]
> > Also, if I'm installing a specific package, it shouldn't update all the others, right?

> Incorrect. This is expected behavior, as WP-CLI uses Composer under the hood.

Actually, you can do a selective update with Composer.

So, `composer update my/package` will only update that individual package, not the rest.

**Comment by javorszky** [comment]
> Actually, you can do a selective update with Composer.

> So, composer update my/package will only update that individual package, not the rest.

That's fine, but if I'm just installing a package, I don't expect all other packages to be touched unless I explicitly tell them to be touched.

Dunno, maybe it's just me and not knowing what to expect of composer.

**Comment by schlessera** [comment]
No, you're right, I think. I would also expect that if I add a package, that that package will get installed in its latest matching version, but the rest just stays as is. I should need to run `wp package update` to get updates to the rest of the packages.
