### ISSUE TITLE
Command to determine if a package is already installed

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/package-command#75]
When installing a package, I only want to run the installer if the package isn't already installed.

Example usage:

```shell
if ! $(wp package is-installed foo/bar); then
	wp package install foo/bar
fi
```

**Comment by danielbachhuber** [comment]
👍 Seems reasonable.

**Comment by schlessera** [comment]
You can already check whether one of the commands that the package provides is available:
```
if ! $(wp cli has-command bar); then
	wp package install foo/bar
fi
```

**Comment by johnbillion** [comment]
Thanks I think checking for a command with `cli has-command` is actually more appropriate than checking for a package name. Closing unless someone disagrees.
