### ISSUE TITLE
Cannot install package from private repo

### ISSUE THREAD

**Issue by NicktheGeek** [wp-cli/package-command#76]
In previous versions of WP-CLI it was possible to install packages from private repos so long as the command line user had access to that repo.

As of at least WP-CLI 1.5.0 this is no longer possible and attempting to install a package from a private repo resulted in an error:
```
wp package install git@github.com:{private/repo}.git
Error: Couldn't download composer.json file from 'https://raw.githubusercontent.com/{private/repo}/master/composer.json' (HTTP code 404).
```

This appears to be a result of the HTTPS for the raw.githubusercontent.com not being authenticated from the command line.

```
curl https://raw.githubusercontent.com/{private/repo}/master/composer.json
404: Not Found
```

This may be a result of https://github.com/wp-cli/package-command/pull/31

**Comment by emirpprime** [comment]
Put together an attempted fix in #78
