### ISSUE TITLE
Installation of any package fails with no error

### ISSUE THREAD

**Issue by phillipp** [wp-cli/package-command#80]
Hi,
I'm trying for a few hours now to install a package, but I fail miserably. I'm trying to set up a global package path (WP_CLI_PACKAGES_DIR=/usr/share/wp-cli/packages) where users have pre-installed packages. For that, I install as root.

```
root@48181fde35ba:/usr/share/wp-cli/packages# wp package install --allow-root --debug wp-cli/admin-command
Debug (bootstrap): No readable global config found (0.071s)
Debug (bootstrap): No project config found (0.071s)
Debug (bootstrap): argv: /usr/local/bin/wp package install --allow-root --debug wp-cli/admin-command (0.071s)
Debug (bootstrap): ABSPATH defined: / (0.071s)
Debug (bootstrap): Running command: package install (0.071s)
Installing package wp-cli/admin-command (dev-master)
Updating /usr/share/wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Reverted composer.json.
```

Cool. Reverted composer.json. Okay, but why? No answer. Because the composer.json is reverted, I don't have it to test a installation with composer itself. So I want and CTRL+C'ed out of wp package install so I get the composer.json. That bringe me to:

```
root@48181fde35ba:/usr/share/wp-cli/packages# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files
```

That seemd to have worked pretty well. So why is wp package failing? I have no idea.

Is there a way to debug this? Can I see any error messages? Looking at https://github.com/wp-cli/package-command/blob/master/src/Package_Command.php#L337 there should be at least SOME messages, but they are not helpful.

I have tested this as non-root user just to be sure. No luck.

**Comment by schlessera** [comment]
@phillipp Are you able to share your `/usr/share/wp-cli/packages/composer.json` file (minus any sensitive information) ?

**Comment by phillipp** [comment]
@schlessera 
Sorry to waste your time. Did found the problem: display_errors was off and memory_limit was not high enough - PHP exited without any message. Config change helped.
