### ISSUE TITLE
Error not shown on "Reverted composer.json"

### ISSUE THREAD

**Issue by etiennejcharles** [wp-cli/package-command#81]
Thanks for the amazing plugin guys! 

Is there any way that the error can be shown ? 
I saw my `composer.json` "File was Reverted", but really had no idea why.

Had to go search in 

https://github.com/wp-cli/package-command/pull/64
https://github.com/wp-cli/package-command/issues/27
https://github.com/wp-cli/wp-cli/issues/4289

In order to understand that my package failed to install because of a "memory limit."

Finally, came across the tests to understand the reasons why that could occur. 

https://github.com/wp-cli/package-command/blob/5182bca582708776ca78e746f4021d473ec94e6e/features/package.feature

Let me know guys!

**Comment by schlessera** [comment]
I agree, we should try to show the reason why the installation failed, especially as this particular one is amongst the most significant support requests we get.

**Comment by wpaustria** [comment]
yeah, that would be great!
